version: '3.1'

services:
  db-django:
    image: simonowens157/postgresql:v1.0
    restart: always
    container_name: standalone-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ${PWD}/data/:/var/lib/postgresql_data
    networks:
      - djangonet
  nginx-django:
    image: simonowens157/nginx:latest
    container_name: standlone-nginx
    restart: always
    environment:
      - VIRTUAL_HOST=ctfapp.owens-netsec.com
      - LETSENCRYPT_HOST=ctfapp.owens-netsec.com
      - LETSENCRYPT_EMAIL=simonowens157@gmail.com
      - VIRTUAL_PORT=80
    networks:
      - djangonet
      - default
  web-django:
    image: simonowens157/django:v1.0
    container_name: standlone-django
    restart: always
    command: ${RUN_ENV}
    stdin_open: true
    tty: true 
    environment:
      - RUN_ENV=${RUN_ENV}
    volumes:
      - ${PWD}/code/:/code
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - djangonet
    depends_on:
      - db-django
      - nginx-django
    
networks:
  djangonet:
  default:
    external:
      name: webproxy
